export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

//gonna be a promise
export const REQUEST_CARS_PENDING = 'REQUEST_CARS_PENDING';
export const REQUEST_CARS_SUCCESS = 'REQUEST_CARS_SUCCESS';
export const REQUEST_CARS_FAILED = 'REQUEST_CARS_FAILED';